SELECT D.DEPARTMENT_NAME "Department", D.LOCATION_ID "Location" , COUNT(*) "Number of Workers", ROUND(AVG(SALARY), 2) "Average Salary"
FROM HR.DEPARTMENTS D, HR.EMPLOYEES E
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME, D.LOCATION_ID;
