/* LAB07_13
Suarez, George
*/

CREATE OR REPLACE VIEW DEPT50 AS
SELECT A.EMPLOYEE_ID "EMPNO", A.LAST_NAME "EMPLOYEE", A.DEPARTMENT_ID "DEPTNO"
FROM HR.EMPLOYEES A
WHERE DEPARTMENT_ID = 50
WITH CHECK OPTION CONSTRAINT emp_dept_50;
