SELECT A.LAST_NAME "Employee", A.HIRE_DATE "Emp Hired", M.LAST_NAME "Manager", M.HIRE_DATE "Mgr Hired"
FROM HR.EMPLOYEES A, HR.EMPLOYEES M
WHERE A.EMPLOYEE_ID = M.MANAGER_ID AND A.HIRE_DATE < M.HIRE_DATE;
